Traceback (most recent call last):
  File "/Users/jirlong/opt/anaconda3/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/jirlong/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/jirlong/opt/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/jirlong/opt/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/jirlong/opt/anaconda3/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/jirlong/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/jirlong/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/jirlong/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# !pip install bertopic
# !pip install hdbscan
# !pip install jieba

from bertopic import BERTopic
from transformers.pipelines import pipeline

from bertopic.vectorizers import ClassTfidfTransformer
from bertopic.representation import KeyBERTInspired
from sklearn.feature_extraction.text import CountVectorizer
import jieba
jieba.load_userdict("data/userdict.txt")

from hdbscan import HDBSCAN

def tokenize_zh(text):
    words = jieba.lcut(text)
    return words

------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Input [0;32mIn [3][0m, in [0;36m<cell line: 5>[0;34m()[0m
[1;32m      1[0m [38;5;66;03m# !pip install bertopic[39;00m
[1;32m      2[0m [38;5;66;03m# !pip install hdbscan[39;00m
[1;32m      3[0m [38;5;66;03m# !pip install jieba[39;00m
[0;32m----> 5[0m [38;5;28;01mfrom[39;00m [38;5;21;01mbertopic[39;00m [38;5;28;01mimport[39;00m BERTopic
[1;32m      6[0m [38;5;28;01mfrom[39;00m [38;5;21;01mtransformers[39;00m[38;5;21;01m.[39;00m[38;5;21;01mpipelines[39;00m [38;5;28;01mimport[39;00m pipeline
[1;32m      8[0m [38;5;28;01mfrom[39;00m [38;5;21;01mbertopic[39;00m[38;5;21;01m.[39;00m[38;5;21;01mvectorizers[39;00m [38;5;28;01mimport[39;00m ClassTfidfTransformer

[0;31mModuleNotFoundError[0m: No module named 'bertopic'
ModuleNotFoundError: No module named 'bertopic'

